# Generated by Django 5.2 on 2025-05-13 12:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'categorie_produit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('point', models.IntegerField()),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_frs', models.AutoField(primary_key=True, serialize=False)),
                ('nom_frs', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('type_frs', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'fournisseur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=250)),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('caissier', 'Caissier')], default='caissier', max_length=8)),
                ('statut', models.CharField(max_length=7)),
                ('fist_login', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.client')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commande',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id_appro', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_frs', models.ForeignKey(db_column='id_frs', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.fournisseur')),
            ],
            options={
                'db_table': 'approvisionnement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantite', models.IntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField()),
                ('stock_min', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseSQL.categorieproduit')),
            ],
            options={
                'db_table': 'produit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entrée', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('aprovisionement', 'Approvisionement'), ('transfert', 'Transfert')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseSQL.produit')),
            ],
            options={
                'db_table': 'mouvement_stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id_lignecmd', models.AutoField(db_column='id_ligneCmd', primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_commande', models.ForeignKey(db_column='id_commande', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.commande')),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.produit')),
            ],
            options={
                'db_table': 'ligne_commande',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneAppro',
            fields=[
                ('id_ligneappro', models.AutoField(db_column='id_ligneAppro', primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id_appro', models.ForeignKey(db_column='id_appro', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.approvisionnement')),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.produit')),
            ],
            options={
                'db_table': 'ligne_appro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfilCaissier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profil_caissier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('sueil_alerte', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.produit')),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_vente', models.AutoField(primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField()),
                ('montanttotal', models.DecimalField(db_column='montantTotal', decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=10)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.client')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id_ligne', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.produit')),
                ('id_vente', models.ForeignKey(db_column='id_vente', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.vente')),
            ],
            options={
                'db_table': 'ligne_vente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.AutoField(primary_key=True, serialize=False)),
                ('code_facture', models.CharField(max_length=100)),
                ('date_emission', models.DateTimeField()),
                ('date_paiement', models.DateTimeField()),
                ('montant_ht', models.DecimalField(db_column='montant_HT', decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(db_column='montant_TTC', decimal_places=2, max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(max_length=11)),
                ('id_vente', models.ForeignKey(db_column='id_vente', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.vente')),
            ],
            options={
                'db_table': 'facture',
                'managed': True,
            },
        ),
    ]
