# Generated by Django 5.2 on 2025-05-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0002_alter_client_adresse_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='id_frs',
            field=models.ForeignKey(db_column='id_frs', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.fournisseur'),
            preserve_default=False,
        ),
    ]
