# Generated by Django 5.2 on 2025-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0003_commande_id_frs'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
