# Generated by Django 5.2 on 2025-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0004_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='codes_barres',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
