# Generated by Django 5.2 on 2025-05-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0005_produit_codes_barres'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)'),
        ),
    ]
