# Generated by Django 5.2 on 2025-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0006_vente_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
