# Generated by Django 5.2 on 2025-05-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0007_approvisionnement_date_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/'),
        ),
    ]
