# Generated by Django 5.2 on 2025-05-29 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0008_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='id_utilisateur',
            field=models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventes', to=settings.AUTH_USER_MODEL),
        ),
    ]
