# Generated by Django 5.2 on 2025-06-11 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0009_alter_vente_id_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RetourProduit',
            fields=[
                ('id_retour', models.AutoField(primary_key=True, serialize=False)),
                ('date_retour', models.DateTimeField(auto_now_add=True)),
                ('raison', models.TextField(blank=True, null=True)),
                ('montant_total_rembourse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilisateur', models.ForeignKey(db_column='id_utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(db_column='id_vente', on_delete=django.db.models.deletion.CASCADE, to='baseSQL.vente')),
            ],
            options={
                'db_table': 'retour_produit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id_ligne_retour', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_rembourse_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.DO_NOTHING, to='baseSQL.produit')),
                ('retour', models.ForeignKey(db_column='id_retour', on_delete=django.db.models.deletion.CASCADE, related_name='lignes_retour', to='baseSQL.retourproduit')),
            ],
            options={
                'db_table': 'ligne_retour',
                'managed': True,
            },
        ),
    ]
