# Generated by Django 5.2 on 2025-06-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0010_alter_client_contact_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='quantite_retournee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
