# Generated by Django 5.2 on 2025-06-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0011_lignevente_quantite_retournee'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
