# Generated by Django 5.2 on 2025-06-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0012_utilisateur_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('entrée', 'Entrée'), ('sortie', 'Sortie'), ('retour', 'Retour'), ('ajustement', 'Ajustement'), ('aprovisionement', 'Approvisionement'), ('transfert', 'Transfert')], max_length=20),
        ),
    ]
