# Generated by Django 5.2 on 2025-06-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseSQL', '0013_alter_mouvementstock_type_mouvement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='fist_login',
        ),
    ]
